// Package lockfile reads and writes conch.lock — the per-project record
// of resolved versions and integrity hashes that lets the same
// environment be reconstructed deterministically on any machine.
//
// Format is TOML, organised as keyed sub-tables rather than arrays of
// entries. PowerShell is per-platform (the binary differs per OS/arch);
// modules are global (the same .nupkg is served regardless of host
// platform):
//
//	version = 1
//
//	[powershell.windows-amd64]
//	version = "7.5.6"
//	url     = "..."
//	sha256  = "..."
//
//	[modules.Pester]
//	version = "5.7.1"
//	url     = "..."
//	sha256  = "..."
//
// Diffs are per-section, ordering is stable, and there's no
// `[[entry]]` array-of-tables noise.
package lockfile

import (
	"bytes"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

// SchemaVersion is bumped when the on-disk format changes in a way old
// conch versions can't read. v1 is the keyed-section format above.
const SchemaVersion = 1

// Lockfile is the in-memory shape of conch.lock.
//
// PowerShell is keyed by platform string ("windows-amd64",
// "linux-amd64", …). Modules are keyed by module name; they are not
// per-platform because PSGallery serves the same .nupkg on every OS.
type Lockfile struct {
	Version    int                     `toml:"version"`
	PowerShell map[string]ResolvedItem `toml:"powershell,omitempty"`
	Modules    map[string]ResolvedItem `toml:"modules,omitempty"`
}

// ResolvedItem is one resolved artefact's record. URL and SHA256 are
// the trust anchor for re-installs: matching SHA256 lets the cache
// short-circuit without re-downloading; URL lets future installs
// avoid re-resolving via upstream metadata.
type ResolvedItem struct {
	Version string `toml:"version"`
	URL     string `toml:"url"`
	SHA256  string `toml:"sha256"`
}

// New returns an empty lockfile pinned to the current schema version.
func New() *Lockfile {
	return &Lockfile{
		Version:    SchemaVersion,
		PowerShell: map[string]ResolvedItem{},
		Modules:    map[string]ResolvedItem{},
	}
}

// Read decodes a lockfile from disk. A missing file is reported via
// os.ErrNotExist; callers can decide whether that's fatal.
func Read(path string) (*Lockfile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var l Lockfile
	if _, err := toml.Decode(string(data), &l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if l.Version == 0 {
		l.Version = SchemaVersion
	}
	if l.Version > SchemaVersion {
		return nil, fmt.Errorf(
			"%s was written by a newer conch (schema v%d, this conch supports v%d)",
			path, l.Version, SchemaVersion,
		)
	}
	if l.PowerShell == nil {
		l.PowerShell = map[string]ResolvedItem{}
	}
	if l.Modules == nil {
		l.Modules = map[string]ResolvedItem{}
	}
	return &l, nil
}

// Write encodes the lockfile to disk. BurntSushi/toml's encoder sorts
// map keys, so the on-disk order is deterministic across runs.
func (l *Lockfile) Write(path string) error {
	l.Version = SchemaVersion

	var buf bytes.Buffer
	buf.WriteString("# conch.lock — generated by conch. Do not edit by hand.\n")
	enc := toml.NewEncoder(&buf)
	enc.Indent = ""
	if err := enc.Encode(l); err != nil {
		return fmt.Errorf("encode lockfile: %w", err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// PutPowerShell records a resolved PowerShell distribution for the
// given platform string. Replaces any prior entry for that platform.
func (l *Lockfile) PutPowerShell(platform string, item ResolvedItem) {
	if l.PowerShell == nil {
		l.PowerShell = map[string]ResolvedItem{}
	}
	l.PowerShell[platform] = item
}

// PutModule records a resolved module. Replaces any prior entry of
// the same name.
func (l *Lockfile) PutModule(name string, item ResolvedItem) {
	if l.Modules == nil {
		l.Modules = map[string]ResolvedItem{}
	}
	l.Modules[name] = item
}

// LookupPowerShell returns the resolved PowerShell for the given
// platform, if any.
func (l *Lockfile) LookupPowerShell(platform string) (ResolvedItem, bool) {
	if l == nil || l.PowerShell == nil {
		return ResolvedItem{}, false
	}
	item, ok := l.PowerShell[platform]
	return item, ok
}

// LookupModule returns the resolved module of the given name, if any.
func (l *Lockfile) LookupModule(name string) (ResolvedItem, bool) {
	if l == nil || l.Modules == nil {
		return ResolvedItem{}, false
	}
	item, ok := l.Modules[name]
	return item, ok
}
