package env

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/jdarcyryan/conch/internal/manifest"
)

// preferenceMapping pairs a TOML preference key with the PowerShell
// preference variable it sets. Booleans, ints, and strings all serialise
// the same way — a single `$VarName = <literal>` line — so we keep one
// flat list and dispatch on the type at write time.
type preferenceMapping struct {
	tomlKey string
	psVar   string
	value   any // *string, *bool, or *int64
}

// WriteActivate writes activate.ps1 into l's `.conch/` directory.
func (l Layout) WriteActivate(m *manifest.Manifest) error {
	body, err := l.ActivateContent(m)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(l.ConchDir(), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", l.ConchDir(), err)
	}
	if err := os.WriteFile(l.ActivateScript(), []byte(body), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", l.ActivateScript(), err)
	}
	return nil
}

// ActivateContent renders the activation script body. Source it from
// an interactive pwsh session (`. .\.conch\activate.ps1`) to enter the
// environment without leaving your current shell.
//
// Paths inside the rendered script are resolved relative to
// $PSScriptRoot — i.e. the directory the script lives in. This means
// .conch/ travels with the project: if you move or copy the project
// directory, the activation script keeps working without
// regeneration. If the script is moved *out* of .conch/, $PSScriptRoot
// points elsewhere and Resolve-Path fails loudly rather than silently
// pointing at a stale absolute path.
func (l Layout) ActivateContent(m *manifest.Manifest) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by conch — do not edit by hand.\n")
	b.WriteString("# Source this script (\". ./.conch/activate.ps1\") to enter the\n")
	b.WriteString("# environment. PSModulePath is rewritten exclusively to the\n")
	b.WriteString("# project's module directory; host modules are not visible.\n")
	b.WriteString("# All paths resolve relative to $PSScriptRoot — moving the\n")
	b.WriteString("# project directory is fine; moving this file out of .conch/\n")
	b.WriteString("# is not.\n\n")

	// PSModulePath isolation.
	//
	// Two paths are exposed to PowerShell: the project modules conch
	// installed into .conch/modules, and the bundled modules that
	// ship with the PowerShell distribution (.conch/pwsh/Modules) —
	// without the latter, even Microsoft.PowerShell.Utility
	// (Add-Member, Out-String, etc.) becomes unreachable.
	//
	// Both paths use Resolve-Path -ErrorAction Stop so a missing
	// directory becomes a hard failure rather than a silent fallback
	// to whatever the host shell had.
	b.WriteString("$conchModules = (Resolve-Path -ErrorAction Stop -LiteralPath (Join-Path $PSScriptRoot 'modules')).Path\n")
	b.WriteString("$pwshBundled = (Resolve-Path -ErrorAction Stop -LiteralPath (Join-Path $PSScriptRoot 'pwsh' 'Modules')).Path\n")
	b.WriteString("$env:PSModulePath = $conchModules + [IO.Path]::PathSeparator + $pwshBundled\n\n")

	// Preferences.
	prefs := orderedPreferences(m.Preferences)
	if len(prefs) > 0 {
		b.WriteString("# Preferences\n")
		for _, p := range prefs {
			line, err := renderPreference(p)
			if err != nil {
				return "", err
			}
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// Tasks → functions.
	if len(m.Tasks) > 0 {
		b.WriteString("# Tasks\n")
		for _, t := range m.Tasks {
			b.WriteString(renderTaskFunction(t))
			b.WriteString("\n")
		}
	}

	return b.String(), nil
}

// orderedPreferences walks m.Preferences in a stable order so the
// generated activate.ps1 doesn't churn between runs.
func orderedPreferences(p manifest.Preferences) []preferenceMapping {
	all := []preferenceMapping{
		{"error", "ErrorActionPreference", p.Error},
		{"warning", "WarningPreference", p.Warning},
		{"verbose", "VerbosePreference", p.Verbose},
		{"debug", "DebugPreference", p.Debug},
		{"information", "InformationPreference", p.Information},
		{"progress", "ProgressPreference", p.Progress},
		{"confirm", "ConfirmPreference", p.Confirm},
		{"error-view", "ErrorView", p.ErrorView},
		{"module-autoload", "PSModuleAutoLoadingPreference", p.ModuleAutoload},
		{"native-arg-passing", "PSNativeCommandArgumentPassing", p.NativeArgPassing},
		{"whatif", "WhatIfPreference", p.WhatIf},
		{"native-error-action", "PSNativeCommandUseErrorActionPreference", p.NativeErrorAction},
		{"format-enum-limit", "FormatEnumerationLimit", p.FormatEnumLimit},
		{"max-history", "MaximumHistoryCount", p.MaxHistory},
		{"ofs", "OFS", p.OFS},
		{"log-command-health", "LogCommandHealthEvent", p.LogCommandHealth},
		{"log-command-lifecycle", "LogCommandLifecycleEvent", p.LogCommandLifecycle},
		{"log-engine-health", "LogEngineHealthEvent", p.LogEngineHealth},
		{"log-engine-lifecycle", "LogEngineLifecycleEvent", p.LogEngineLifecycle},
		{"log-provider-health", "LogProviderHealthEvent", p.LogProviderHealth},
		{"log-provider-lifecycle", "LogProviderLifecycleEvent", p.LogProviderLifecycle},
	}
	out := all[:0]
	for _, p := range all {
		if !isNil(p.value) {
			out = append(out, p)
		}
	}
	return out
}

// isNil treats a typed-nil pointer as nil, matching what the manifest
// validator produces for unset optional preferences.
func isNil(v any) bool {
	switch x := v.(type) {
	case *string:
		return x == nil
	case *bool:
		return x == nil
	case *int64:
		return x == nil
	}
	return v == nil
}

func renderPreference(p preferenceMapping) (string, error) {
	switch v := p.value.(type) {
	case *string:
		return fmt.Sprintf("$%s = %s", p.psVar, PSSingleQuote(*v)), nil
	case *bool:
		return fmt.Sprintf("$%s = $%t", p.psVar, *v), nil
	case *int64:
		return fmt.Sprintf("$%s = %s", p.psVar, strconv.FormatInt(*v, 10)), nil
	}
	return "", fmt.Errorf("unsupported preference type for %s", p.tomlKey)
}

func renderTaskFunction(t manifest.Task) string {
	var b strings.Builder
	b.WriteString("function ")
	b.WriteString(taskFunctionName(t.Name))
	b.WriteString(" {\n")
	for _, line := range t.Lines {
		b.WriteString("    ")
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// taskFunctionName converts a manifest task name into a PowerShell
// function name. Hyphens are common in task names ("test-ci"); they
// are preserved because they're valid in PS function names.
func taskFunctionName(name string) string {
	return "conch_task_" + name
}

// PSSingleQuote renders s as a PowerShell single-quoted literal. Single
// quotes inside the input are doubled, matching PowerShell's escape
// convention.
func PSSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// TaskScript returns the PowerShell snippet that runs `name` after the
// activation script has been sourced. This is what `conch run` feeds
// to pwsh -Command.
//
// activate.ps1 itself uses $PSScriptRoot for relative resolution — so
// here we sourcing it via its absolute path is fine: $PSScriptRoot is
// computed from however the script is invoked, not from the calling
// shell's CWD.
func (l Layout) TaskScript(name string) string {
	return fmt.Sprintf(". %s\n%s",
		PSSingleQuote(l.ActivateScript()), taskFunctionName(name))
}
