// Package env owns the on-disk layout of a conch environment (the
// `.conch/` directory beside the manifest) and generates the activation
// script that puts a shell into it.
//
// Layout:
//
//	<project>/
//	  conch.toml
//	  conch.lock
//	  .conch/
//	    pwsh/                  # extracted PowerShell distribution
//	      pwsh, pwsh.exe       # entry point depends on platform
//	    modules/               # PSModulePath target
//	      <Module>/<Version>/...
//	    activate.ps1           # generated by `conch install`
//
// Everything under `.conch/` is conch-managed: it is regenerated by
// `conch install` from the manifest + lockfile, and the directory is
// added to `.gitignore` automatically.
package env

import (
	"path/filepath"

	"github.com/jdarcyryan/conch/internal/platform"
)

// Layout collects the on-disk paths conch cares about for one project.
// Construct it from a project root; everything else is computed.
type Layout struct {
	ProjectRoot string
}

// New returns a Layout rooted at the given project directory.
func New(projectRoot string) Layout {
	return Layout{ProjectRoot: projectRoot}
}

// ConchDir returns the absolute path of the project's `.conch/`
// directory.
func (l Layout) ConchDir() string { return filepath.Join(l.ProjectRoot, ".conch") }

// PowerShellDir returns the directory the extracted PowerShell
// distribution lives in.
func (l Layout) PowerShellDir() string { return filepath.Join(l.ConchDir(), "pwsh") }

// ModulesDir returns the project-installed modules directory.
//
// Note that this is *not* the entirety of PSModulePath: the bundled
// modules that ship inside the PowerShell distribution itself
// (Microsoft.PowerShell.Utility, Microsoft.PowerShell.Management, …)
// also need to be on the path or essentials like Add-Member break.
// See BundledModulesDir for that pair.
func (l Layout) ModulesDir() string { return filepath.Join(l.ConchDir(), "modules") }

// BundledModulesDir returns the modules directory that ships inside
// the extracted PowerShell distribution. PSModulePath always pairs
// this with ModulesDir() so engine-bundled cmdlets keep working.
func (l Layout) BundledModulesDir() string { return filepath.Join(l.PowerShellDir(), "Modules") }

// ActivateScript returns the path of the generated activate.ps1.
func (l Layout) ActivateScript() string { return filepath.Join(l.ConchDir(), "activate.ps1") }

// LockfilePath returns the path of conch.lock.
func (l Layout) LockfilePath() string { return filepath.Join(l.ProjectRoot, "conch.lock") }

// ManifestPath returns the path of conch.toml.
func (l Layout) ManifestPath() string { return filepath.Join(l.ProjectRoot, "conch.toml") }

// PowerShellExecutable returns the absolute path to pwsh inside the
// environment for the given platform.
func (l Layout) PowerShellExecutable(p platform.Platform) string {
	if p.OS == platform.Windows {
		return filepath.Join(l.PowerShellDir(), "pwsh.exe")
	}
	return filepath.Join(l.PowerShellDir(), "pwsh")
}
